# Generated by Django 5.1 on 2025-08-31 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='weight',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, message='Вес не может быть меньше 1'), django.core.validators.MaxValueValidator(10, message='Вес не может быть больше 10')]),
        ),
    ]
